image: alpine:latest

stages:
  - deploy

before_script:
  - apk add --no-cache openssh-client git
  - eval $(ssh-agent -s)
  - echo "$GITHUB_SSH_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan github.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts

sync_to_github:
  stage: deploy
  only:
    - dev   # 只在 dev 分支触发
  script:
    - git remote remove github || true
    - git remote add github git@github.com:xingwanyue/det-portal-i18n.git
    - git push --mirror github
