export default [
  {
    '@context': 'https://schema.org',
    '@type': 'EducationalOrganization',
    name: 'DET Practice',
    legalName: 'AITOGETHER LTD',
    url: 'https://www.detpractice.com/',
    logo: 'https://www.detpractice.com/img/footer/small_logo.svg',
    image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
    description:
      'DET Practice provides global online preparation services for the Duolingo English Test with 18,000+ practice questions, AI-powered correction services, full-length mock exams, and comprehensive courses available worldwide.',
    foundingDate: '2020',
    telephone: '+447518886018',
    email: 'support@detpractice.com',
    areaServed: 'Worldwide',
    availableLanguage: ['en', 'id', 'ja', 'ko', 'ru', 'tr', 'de', 'es', 'fr', 'it', 'th', 'zh', 'pt'],
    address: {
      '@type': 'PostalAddress',
      streetAddress: '71-75 Shelton Street, Covent Garden',
      addressLocality: 'London',
      addressRegion: 'England',
      postalCode: 'WC2H 9JQ',
      addressCountry: 'UK',
    },
    location: {
      '@type': 'Place',
      name: 'Corporate Headquarters',
      address: {
        '@type': 'PostalAddress',
        streetAddress: '71-75 Shelton Street, Covent Garden',
        addressLocality: 'London',
        addressRegion: 'England',
        postalCode: 'WC2H 9JQ',
        addressCountry: 'UK',
      },
    },
    sameAs: [
      'https://www.facebook.com/detpractice',
      'https://x.com/det_practice',
      'https://www.instagram.com/detpractice/',
      'https://twitter.com/det_practice',
    ],
    aggregateRating: {
      '@type': 'AggregateRating',
      ratingValue: '4.8',
      bestRating: '5',
      worstRating: '1',
      reviewCount: '850',
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'WebSite',
    name: 'DET Practice - Ace the Duolingo English Test',
    url: 'https://www.detpractice.com/',
    inLanguage: 'en',
    potentialAction: {
      '@type': 'SearchAction',
      target: 'https://www.detpractice.com/search?q={search_term_string}',
      'query-input': 'required name=search_term_string',
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'WebPage',
    name: 'DET Practice - Ace the Duolingo English Test',
    description:
      'DET Practice is the best platform for Duolingo English Test preparation with 18,000+ practice questions, AI-powered correction services, full-length mock exams, and comprehensive courses.',
    url: 'https://www.detpractice.com/',
    inLanguage: 'en',
    datePublished: '2020-01-01T00:00:00Z',
    dateModified: '2025-03-07T14:30:00Z',
    publisher: {
      '@type': 'Organization',
      name: 'DET Practice',
      logo: {
        '@type': 'ImageObject',
        url: 'https://www.detpractice.com/img/footer/small_logo.svg',
      },
    },
  },
  {
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        item: {
          '@type': 'SoftwareApplication',
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Web',
          name: 'DET Practice Question Bank',
          description: 'The largest question bank with 18,000+ practice questions, continuously updated every day.',
          url: 'https://www.detpractice.com/practice',
          image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
          inLanguage: 'en',
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'USD',
            areaServed: 'Worldwide',
            availableDeliveryMethod: 'http://schema.org/OnlineDelivery',
          },
        },
      },
      {
        '@type': 'ListItem',
        position: 2,
        item: {
          '@type': 'SoftwareApplication',
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Web',
          name: 'DET Full-Length Mock Test',
          description: 'The most powerful mock test, close to real DET exam with adaptive exams and AI scoring.',
          url: 'https://www.detpractice.com/mock-test',
          image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
          inLanguage: 'en',
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'USD',
            areaServed: 'Worldwide',
            availableDeliveryMethod: 'http://schema.org/OnlineDelivery',
          },
        },
      },
      {
        '@type': 'ListItem',
        position: 3,
        item: {
          '@type': 'SoftwareApplication',
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Web',
          name: 'DET Writing AI Correction',
          description: 'AI-powered writing correction service for all DET writing question types.',
          url: 'https://www.detpractice.com/writing-correction',
          image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
          inLanguage: 'en',
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'USD',
            areaServed: 'Worldwide',
            availableDeliveryMethod: 'http://schema.org/OnlineDelivery',
          },
        },
      },
      {
        '@type': 'ListItem',
        position: 4,
        item: {
          '@type': 'SoftwareApplication',
          applicationCategory: 'EducationalApplication',
          operatingSystem: 'Web',
          name: 'DET Speaking AI Correction',
          description: 'AI-powered speaking correction service for all DET speaking question types.',
          url: 'https://www.detpractice.com/speaking-correction',
          image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
          inLanguage: 'en',
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'USD',
            areaServed: 'Worldwide',
            availableDeliveryMethod: 'http://schema.org/OnlineDelivery',
          },
        },
      },
      {
        '@type': 'ListItem',
        position: 5,
        item: {
          '@type': 'Course',
          name: 'Duolingo English Test Course',
          description: 'Develop an in-depth understanding of DET speaking and writing sections with detailed guides.',
          url: 'https://www.detpractice.com/courses',
          image: 'https://www.detpractice.com/store/portal/products/bank_picture1.png',
          inLanguage: 'en',
          provider: {
            '@type': 'Organization',
            name: 'DET Practice',
            sameAs: 'https://www.detpractice.com/',
          },
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',

            priceCurrency: 'USD',
            areaServed: 'Worldwide',
            availableDeliveryMethod: 'http://schema.org/OnlineDelivery',
          },
        },
      },
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      {
        '@type': 'ListItem',
        position: 1,
        name: 'Home',
        item: 'https://www.detpractice.com/',
      },
      {
        '@type': 'ListItem',
        position: 2,
        name: 'Blog',
        item: 'https://www.detpractice.com/blog',
      },
    ],
  },
  {
    '@context': 'https://schema.org',
    '@type': 'Course',
    name: 'Duolingo English Test Preparation Course',
    description:
      'Comprehensive preparation for the Duolingo English Test covering all test sections including reading, writing, speaking, and listening.',
    inLanguage: 'en',
    url: 'https://www.detpractice.com/courses',
    provider: {
      '@type': 'Organization',
      name: 'DET Practice',
      sameAs: 'https://www.detpractice.com/',
    },
  },
];
